ajout des tests back

diff --git a/.github/workflows/ci-tests.yml b/.github/workflows/ci-tests.yml
--- a/.github/workflows/ci-tests.yml
+++ b/.github/workflows/ci-tests.yml
@@ -6,6 +6,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
       - name: launch front tests with coverage
         run: |
             cd front
@@ -14,18 +15,28 @@ jobs:
             npm run test:ci-coverage
             cd ..
 
-    - name: Set up JDK 17
-      uses: actions/setup-java@v3
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-        cache: maven
-    - name: launch maven compile with tests with coverage
-      run: |
-        cd back
-        mvn -B compile
-      - uses: actions/upload-artifact@v4  # upload test results
-        if: success() || failure()        # run this step even if previous step failed
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
         with:
-          name: test-back-results
-          path: ./back/target/site/jacoco
+          java-version: '17'
+          distribution: 'temurin'
+          cache: maven
+
+      - name: Launch maven compile with tests and coverage
+        run: |
+          cd back
+          mvn -B compile test
+    
+      - name: Upload back test results
+        uses: actions/upload-artifact@v4  # 
+          if: success() || failure()        # run this step even if previous step failed
+          with:
+            name: test-back-results
+            path: ./back/target/site/jacoco
+
+      - name: Upload front test results
+        uses: actions/upload-artifact@v4  # 
+          if: success() || failure()        # run this step even if previous step failed
+          with:
+            name: test-front-results
+            path: ./front/coverage/
